### ISSUE TITLE
Add s3 access point

### ISSUE THREAD

**Issue by Dltmd202** [Dltmd202/10-HaYangSongE-BE-Spring#6]
### `.travis.yml`
```yml

before_deploy:
  - zip -r 10-HaYangSongE-BE-Spring
  - mkdir -p deploy
  - mv 10-HaYangSongE-BE-Spring.zip deploy/10-HaYangSongE-BE-Spring.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: vacstage-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
```
